baseURL = 'https://zhenyan774.github.io/'
<<<<<<< HEAD
languageCode = 'zh-cn'
title = '我的个人作品集'
=======
languageCode = 'en-us'
title = 'Zhenyan Zhang | Quant Research & Trder'
>>>>>>> de406c57375444af07fb2e1abea54c1a03993b68
theme = 'PaperMod'

# 核心：修复 "Author" 报错需要加这个
[author]
    name = "你的名字"

[params]
    env = "production"
    description = "我的个人简历网站"
    author = "你的名字"

    # 首页配置
    [params.homeInfoParams]
        Title = "你好，我是 [你的名字] 👋"
        Content = "欢迎来到我的个人网站。我是一名正在寻找实习/工作的学生，专注于 [你的领域]。"

    # 社交链接
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/[你的用户名]"
    [[params.socialIcons]]
<<<<<<< HEAD
        name = "email"
        url = "mailto:your-email@example.com"

# 解决你截图中的 HTML 警告
[markup.goldmark.renderer]
    unsafe = true
=======
        name = "linkedin"
        url = "https://linkedin.com/in/ZhenyanZhang1556510774" # 记得换成真的
>>>>>>> de406c57375444af07fb2e1abea54c1a03993b68
