bbaseURL = 'https://zhenyan774.github.io/'
languageCode = 'en-us'
title = 'Zhenyan Zhang | Quant Research'
theme = 'PaperMod'

[author]
    name = "Zhenyan Zhang"

[params]
    env = "production"
    # 让你的公式能漂亮显示 (量化必备)
    math = true 

    [params.homeInfoParams]
        Title = "Hello, I'm Zhenyan Zhang 👋"
        # 使用三引号，防止 Master's 的单引号报错
        Content = """
        I am interested in understanding the mechanisms behind financial market behavior. My work combines mathematics, statistical modeling, and machine learning to study financial phenomena and translate these insights into quantitative trading strategies and risk management tools. I am currently pursuing a Master’s degree in Financial Engineering, while actively developing systematic trading models and exploring how mathematical frameworks can help explain and navigate real market dynamics.
        """

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/zhenyan774"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://linkedin.com/in/ZhenyanZhang1556510774" # 记得换成真的